# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: ci-cd
---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  namespace: ci-cd
---
# Role for Jenkins
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ci-cd
  name: jenkins-deployer
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "services", "deployments"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployer-binding
  namespace: ci-cd
subjects:
  - kind: ServiceAccount
    name: jenkins-sa
    namespace: ci-cd
roleRef:
  kind: Role
  name: jenkins-deployer
  apiGroup: rbac.authorization.k8s.io
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-backend-deployment
  namespace: ci-cd
  labels:
    app: fullstack-backend
    environment: production
    version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fullstack-backend
  template:
    metadata:
      labels:
        app: fullstack-backend
        environment: production
        version: "1.0.0"
    spec:
      serviceAccountName: jenkins-sa
      containers:
      - name: fullstack-backend-container
        image: deepakvetrivel97/fullstack-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: fullstack-backend-service
  namespace: ci-cd
spec:
  selector:
    app: fullstack-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
